language: python
python:
  - '2.7'
  - '3.6'
  - "pypy"
install:
  - pip install pip pybuilder coveralls --upgrade
  - pyb install_dependencies
script:
  - pyb -X verify
after_success:
  - coveralls --verbose
